all:
		g++ -std=c++14 SocketServer.cpp -o SocketServer
		g++ -std=c++14 SocketClient.cpp -o SocketClient
debug:
		g++ -g -std=c++14 SocketServer.cpp -o SocketServer
		g++ -g -std=c++14 SocketClient.cpp -o SocketClient
opt:
		g++ -O -std=c++14 SocketServer.cpp -o SocketServer
		g++ -O -std=c++14 SocketClient.cpp -o SocketClient
clean:
		rm SocketServer SocketClient
