all:
		g++ -O SocketServer.c -o SocketServer
		g++ -O SocketClient.c -o SocketClient
debug:
		g++ -g SocketServer.c -o SocketServer
		g++ -g SocketClient.c -o SocketClient
clean:
		rm SocketServer SocketClient
